mds_dashboard:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'mds_dashboard.duckdb'
      schema: dev
    prod:
      type: duckdb
      path: 'mds_dashboard.duckdb'
      schema: prod
